# Exposes the VPC and subnet values generated by the local networking module.
output "vpc_id" {
  value = module.vpc.vpc_id
}
output "module_public_subnets" {
  value = module.vpc.public_subnets
}

output "module_priavte_subnets" {
  value = module.vpc.private_subnets
}